name: Python Cron Job

on:
  schedule:
    - cron: "0 2 * * *"   # 每天 UTC 02:00 运行
  workflow_dispatch:     # 允许手动点击运行

jobs:
  run-python:
    runs-on: ubuntu-latest
    environment: TestEnv # 指定环境，方便那环境变量

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          # 如果你有 requirements.txt，就打开下面一行
          # pip install -r requirements.txt

      - name: Run script
        run: |
          python main.py
